### ISSUE TITLE
Basic documentation

### ISSUE THREAD

**Issue by Guitlle** [rfcx/rfcx-guardian-android#3]
Hi. I am Guillermo. I am from Guatemala. A couple of friends and I are thinking on using your android app to build a prototype of rfcx. We know you guys must be very busy and may not have time for this but we would like to see some basic documentation regarding the usage of this code. We need to know what  each module does and how you install it and use it. 

Regards.

**Comment by topherwhite** [comment]
Hi @DuGuille thanks for your request and your team's interest in setting up a system!

We are not likely to have the chance to add the documentation that you've request before the end of the year, since when we do, we'll want to take some time to make it useful and at least semi-comprehensive. In the meantime, we would be happy to chat with you and/or your team directly to help you get set up with this software. The simplest way might _not_ require you to build/configure the app(s) from source, and it might make more sense for you to just download the existing releases of the software as APKs.

At the moment, the primary requirements for running a full feature of the RFCx software on Android are:
1. The Android smartphone should be _rooted_
2. The phone must be running Android 2.3.7 or higher (API level 10)
3. The phone must have a micro-SD card for data storage/caching.
4. Each phone will need to be given a unique API key for authentication to our web services.

I hope that helps! Please reach out to use directly at contact@rfcx.org to set up a time to speak together. Thanks!

**Comment by egrueter-dev** [comment]
Hi @topherwhite 

Is this project still ongoing? I am working on a project called Hikma that will provide a mobile Electronic Medical Record (EMR) To refugees in locations where wifi will not be available. 

Using cell network to transfer data rather than syncing data to wifi later could be a valuable feature to us. How did you achieve this? Are there any specific areas of the code that I can look at? 

Documenting these modules and describing how they fit into your larger system would be very useful.

Thanks very much,
Erik
